import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Game from "../components/Game";
import Result from "../components/Result";
import { useTheme } from "../hooks/useTheme";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const [step, setStep] = useState(0);
  const [correct, setCorrect] = useState(0);
  const [checked, setChecked] = useState<boolean>(false);
  const { theme, setTheme } = useTheme();

  interface Types {
    title: string;
    variants: string[];
    correct: number;
  }

  const questions: Types[] = [
    {
      title: "React - это ... ?",
      variants: ["библиотека", "фреймворк", "приложение"],
      correct: 0,
    },
    {
      title: "Компонент - это ... ",
      variants: [
        "приложение",
        "часть приложения или страницы",
        "то, что я не знаю что такое",
      ],
      correct: 1,
    },
    {
      title: "Что такое JSX?",
      variants: [
        "Это простой HTML",
        "Это функция",
        "Это тот же HTML, но с возможностью выполнять JS-код",
      ],
      correct: 2,
    },
  ];

  const question = questions[step];

  const onClickStep = (index: number) => {
    setStep(step + 1);
    if (index === question.correct) {
      setCorrect(correct + 1);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <label className={styles.switch}>
        <input
          type="checkbox"
          onChange={() => {
            setChecked((prevState) => !prevState);
            checked ? setTheme("light") : setTheme("dark");
          }}
        />
        <span className={styles.slider + " " + styles.round}></span>
      </label>

      {step !== questions.length ? (
        <Game
          questions={questions}
          step={step}
          question={question}
          onClickStep={onClickStep}
        />
      ) : (
        <Result correct={correct} questions={questions} />
      )}
    </div>
  );
};

export default Home;
